### ISSUE TITLE
convert to XML spec

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/taskview_fda#4]
as in ctv r-forge repo, e.g.

https://r-forge.r-project.org/scm/viewvc.php/pkg/inst/ctv/Bayesian.ctv?view=markup&revision=2543&root=ctv

**Comment by toreerdmann** [comment]
I just pushed a version in xml format. I appended a short script with some regex calls I used.

`ll = readLines("CRAN_task_view_fda.md")
## replace headers...
ll = sub("[#]+ ((\\w+ ?)*).*$", replacement = "</ul>\n\n<p> <strong> \\1 </strong></p> \n\n<ul>", ll)
## and lines that start with bullet points
ll = sub("[*] (The )?\\[(.*)\\](\\(https.*.html\\))(.*)$", replacement = "<li>\\1<pkg>\\2</pkg>\\4</li>", ll)
cat(ll, sep = "\n", file = "tmp.xml")
source("helper.R")
pkgs = extract_pkgs("CRAN_task_view_fda.md")
cat("<packagelist>\n ",
    paste0("<pkg>", pkgs, "</pkg>\n "),
    "\n</packagelist>", file = "packagelist.xml")
# file.remove("tmp.xml", "packagelist.xml")
`
